--TAO BANG MYMARK
SELECT * INTO MYMARK FROM MARK
--TAO AFTER TRIGGER TREN MYMARK 
--DEM SO DONG BI XOA
CREATE TRIGGER DELETEONMYMARK
ON MYMARK
AFTER DELETE
AS
DECLARE @COUNT INT
SELECT @COUNT = COUNT(*) FROM DELETED
PRINT 'YOU HAVE DELETED '+ CAST(@COUNT AS VARCHAR(2))+' RECORD(S)'

SELECT * FROM MYMARK
--KIEM THU TRIGGER
DELETE FROM MYMARK W
WHERE MARK < 10
--TAO AFTER TRIGGER TREN MYMARK 
--DEM SO DONG DUOC CHEN VAO
CREATE TRIGGER INSERTONMYMARK
ON MYMARK
AFTER INSERT
AS
DECLARE @COUNT INT
SELECT @COUNT = COUNT(*) FROM INSERTED
PRINT 'YOU HAVE INSERTED '+ CAST(@COUNT AS VARCHAR(2))+' RECORD(S)'
--
INSERT INTO MYMARK(ROLLNO,SUBJECTCODE,WMARK,PMARK)
(SELECT ROLLNO,SUBJECTCODE,WMARK,PMARK FROM MARK)

--TRIGGER DAM BAO RANG CAC BAN GHI LIEN QUAN DEN CLASS
--SE BI XOA KHI XOA DL TU CLASS
DROP TRIGGER DELETECASCADINGONCLASS
CREATE TRIGGER DELETECASCADINGONCLASS
ON CLASS
INSTEAD OF DELETE
AS
--XOA BANG MARK
DELETE MARK FROM MARK M INNER JOIN STUDENT S
			ON M.ROLLNO = S.ROLLNO 
WHERE S.CLASSCODE IN (SELECT CLASSCODE FROM DELETED)
--XOA BANG STUDENT
DELETE FROM STUDENT 
	   WHERE CLASSCODE IN (SELECT CLASSCODE FROM DELETED)
--XOA CLASS
DELETE FROM CLASS
	   WHERE CLASSCODE IN (SELECT CLASSCODE FROM DELETED)
--KIEM THU TRIGGER
DELETE FROM CLASS WHERE CLASSCODE = 'C0611L'
SELECT * FROM STUDENT 					
SELECT * FROM MARK
--XEM DN TRIGGER
SP_HELPTEXT INSERTONMYMARK
--
SELECT DEFINITION 
FROM SYS.TRIGGERS T INNER JOIN SYS.SQL_MODULES M
ON T.OBJECT_ID = M.OBJECT_ID
WHERE T.NAME='INSERTONMYMARK'
--DDL TRIGGER CHO LENH TAO BANG (CREATE_TABLE)
CREATE TRIGGER CREATE_PERMISSION
ON DATABASE
FOR CREATE_TABLE
AS
BEGIN
	PRINT 'YOU DO NOT HAVE PERMISSION'
	ROLLBACK 
END
--KIEM THU TRIGGER
DROP TABLE MYTEST
CREATE TABLE MYTEST(COL1 INT, COL2 CHAR(1))

DROP TRIGGER CREATE_PERMISSION ON DATABASE