use THU
GO

IF EXISTS(SELECT NAME FROM SysObjects
   WHERE NAME = 'T1' and TYPE='U')
   DROP TABLE T1
IF EXISTS(SELECT NAME FROM SysObjects
   WHERE NAME = 'T2' and TYPE='U')
   DROP TABLE T2
IF EXISTS(SELECT NAME FROM SysObjects
   WHERE NAME = 'T3' and TYPE='U')
   DROP TABLE T3
GO   
CREATE TABLE T1(c1 VARCHAR(10), c2 int) 
CREATE TABLE T2(c1 VARCHAR(10), c2 int) 
CREATE TABLE T3(c1 VARCHAR(10), c2 int) 
GO
INSERT INTO T1 values('A01', 11)
INSERT INTO T1 values('A02', 12)

INSERT INTO T2 values('B01', 21)
INSERT INTO T2 values('B02', 22)
INSERT INTO T2 values('B03', 23)

INSERT INTO T3 values('C01', 31)
INSERT INTO T3 values('C02', 32)
INSERT INTO T3 values('C03', 33)
INSERT INTO T3 values('C04', 34)
GO
IF EXISTS(SELECT NAME FROM SysObjects
   WHERE NAME = 'v1' and TYPE='V')
   DROP VIEW v1
GO
CREATE VIEW v1
AS
SELECT *
FROM T1
   UNION ALL
SELECT *
FROM T2
   UNION ALL
SELECT *
FROM T3
GO
select * from v1
GO
