USE QLDIEM
GO
DROP TABLE MYCLASS

SELECT * INTO MYCLASS FROM CLASS

SELECT * FROM MYCLASS WITH(INDEX=IX_CLASSCODE)
WHERE STUD_NO >= 15
WHERE CLASSCODE IN ('C0609M','C0611L','T0611H')

CREATE NONCLUSTERED INDEX IX_CLASSCODE
ON MYCLASS(CLASSCODE DESC)

INSERT INTO MYCLASS 
VALUES(
'C0504L',
'VU TRAN',
'CLASS1, LAB1',
'17:30 - 21:30',
23,
'8-24-2009'
)
--TAO CHI MUC INDEX2 TREN COT HEADTEACHER CUA BANG 
--MYCLASS
IF EXISTS(SELECT * FROM SYSINDEXES 
			WHERE NAME='MYINDEX1')
	DROP INDEX MYCLASS.MYINDEX1
GO
CREATE CLUSTERED INDEX MYINDEX1 
ON MYCLASS(CLASSCODE DESC) WITH(FILLFACTOR=80)

CREATE NONCLUSTERED INDEX MYINDEX2
ON MYCLASS(HEADTEACHER) INCLUDE(ROOM,CLOSEDATE)

ALTER INDEX MYINDEX1 ON MYCLASS REBUILD

SELECT * FROM MYCLASS WITH(INDEX = MYINDEX1)



SP_HELPINDEX MYCLASS