select * from subject
SP_HELP subject
--THU TUC CHEN 01 BAN GHI VAO SUBJECT
--THONG BAO LOI NEU CHEN THAT BAI
GO
ALTER PROC ADDTOSUBJECT
@SUBJECTCODE VARCHAR(10),
@SUBJECTNAME VARCHAR(40),
@WTEST BIT,
@PTEST BIT,
@WTEST_PER SMALLINT
AS
--PK LA NULL
IF @SUBJECTCODE IS NULL
	RETURN -1
--PK LA RONG
IF @SUBJECTCODE = ''
	RETURN -1
--TRUNG PK
IF EXISTS(SELECT * FROM SUBJECT WHERE SUBJECTCODE = @SUBJECTCODE)
	RETURN -1
INSERT INTO SUBJECT(SUBJECTCODE,
SUBJECTNAME,
WTEST,
PTEST,
WTEST_PER
) VALUES
(@SUBJECTCODE,
@SUBJECTNAME,
@WTEST,
@PTEST,
@WTEST_PER
)
RETURN 0
--THUC THI THU TUC
DECLARE @STATUS INT
EXEC @STATUS = ADDTOSUBJECT 'JAVA','JAVA',1,1,50
IF @STATUS <> 0 --ERROR
	PRINT 'KHONG THE THEM BAN GHI NAY'
ELSE
	PRINT 'THEM MOI THANH CONG'
--TAO TRIGGER TREN BANG SUBJECT
--DAM BAO RANG GIA TRI CUA WTEST_PER KO VUOT QUA 70 KHI CHEN
CREATE TRIGGER INSERTONSUBJECT
ON SUBJECT
FOR INSERT
AS
IF (SELECT WTEST_PER FROM INSERTED) > 70
BEGIN
	PRINT 'WTEST_PER KHONG > 70'
	ROLLBACK TRAN
END
--KIEM THU TRIGGER
INSERT INTO SUBJECT(SUBJECTCODE,SUBJECTNAME,
WTEST,PTEST,WTEST_PER
)VALUES('C#','C#',1,1,80)

SELECT * FROM SUBJECT
--TRIGGER TREN BANG MARK DAM BAO RANG
--KHONG THE XOA NHUNG HS DA DU THI MON CF
SELECT * FROM SYSOBJECTS WHERE NAME ='DELETEONMARK'
DROP TRIGGER DELETEONSTUDENT
CREATE TRIGGER DELETEONMARK
ON MARK
FOR DELETE
AS
IF EXISTS (SELECT * FROM DELETED WHERE SUBJECTCODE = 'CF')
BEGIN
	PRINT 'CAN NOT DELETE THIS RECORD'
	ROLLBACK TRANSACTION
END
--KIEM THU TRIGGER
DELETE FROM MARK WHERE ROLLNO = 'B04'

SELECT *
FROM MARK

--TRIGGER UPDATE TREN BANG STUDENT
--DAM BAO RANG TUOI HVIEN LUON >= 18


UPDATE STUDENT
SET BIRTHDATE = GETDATE()
WHERE ROLLNO = 'A002'
--UPDATE MUC BANG
CREATE TRIGGER DELETEONSTUDENT
ON STUDENT
FOR UPDATE
AS
IF EXISTS(SELECT * FROM INSERTED WHERE YEAR(GETDATE()) - YEAR(BIRTHDATE) < 18)
BEGIN
	PRINT 'CON BE QUA'
	ROLLBACK TRAN
END
--UPDATE MUC COT
--TRIGGER DAM BAO GIA TRI CUA ROLLNO TREN STUDENT KO
--DUOC THAY DOI
--COT ROLLNO THI CAM CAP NHAT -> UPDATE MUC COT
ALTER TRIGGER UPDATEONSTUDENT
ON STUDENT
FOR UPDATE
AS
--IF (SELECT ROLLNO FROM INSERTED) <> (SELECT ROLLNO FROM DELETED)
IF UPDATE(ROLLNO)
BEGIN
	PRINT 'ROLLNO CAN NOT BE UPDATABLE'
	ROLLBACK TRAN
END
--KIEM THU TRIGGER
UPDATE STUDENT
SET ROLLNO = 'C006'
WHERE ROLLNO = 'C06'
--TRIGGER DELETE TREN MARK DAM BAO RANG
--SO BAN GHI BI XOA KHONG > 1 (TAI 1 THOI DIEM)
CREATE TRIGGER DELETEONMARKS
ON MARK
FOR DELETE
AS
IF (SELECT COUNT(*) FROM DELETED) > 1
BEGIN
	PRINT 'CHI DUOC XOA 1 BAN GHI TAI 1 THOI DIEM'
	ROLLBACK TRAN
END
--KIEM THU TRIGGER
DELETE FROM MARK WHERE ROLLNO = 'B03' --OK

SELECT *
FROM MARK