USE QLDIEM
GO
--XEM CAC BANG TRONG CSDL HIEN TAI
SELECT * 
FROM SYSOBJECTS 
WHERE TYPE='U'
--U: BANG
--V: VIEW
--P: STORED PROCEDURE
--TR: TRIGGER
--XEM DL BANG MARK
SELECT *
FROM MARK
--TAO VIEW CHUA DL CUA BANG MARK VOI GIA TRI MARK >=10
CREATE VIEW MARKVIEW
AS
SELECT * 
FROM MARK
WHERE MARK >=10
--XEM DL TRONG VIEW
SELECT *
FROM MARKVIEW
--TAO VIEW LAY TEN SV CO DIEM TRUNG BINH >= 10
CREATE VIEW STUDENTVIEW
AS
SELECT S.FULLNAME
FROM STUDENT S INNER JOIN MARK M
ON S.ROLLNO = M.ROLLNO
WHERE M.MARK >= 10
--XEM DL TU STUDENTVIEW
SELECT *
FROM STUDENTVIEW
--VI DU VE MENH DE COMPUTE, COMPUTE BY
SELECT * 
FROM MARK
COMPUTE MAX(MARK),MIN(MARK),AVG(MARK),SUM(MARK)
--COMPUTE BY
SELECT * 
FROM MARK
ORDER BY ROLLNO
COMPUTE MAX(MARK),MIN(MARK),AVG(MARK) BY ROLLNO
--SUA DOI STUDENTVIEW: VIEW HIEN THI SO MON DA DU THI
--CUA TUNG SV
CREATE VIEW STUDENTVIEW
AS
SELECT ROLLNO AS 'MA SV',COUNT(ROLLNO) AS 'SO MON THI'
FROM MARK
GROUP BY ROLLNO


SELECT *
FROM STUDENTVIEW
--TANG SO MON THI CUA CAC SV LEN 1 (BI LOI)
UPDATE STUDENTVIEW
SET [SO MON THI] = [SO MON THI] + 1
--XOA VIEW STUDENTVIEW
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'STUDENTVIEW' AND TYPE='V')	
	DROP VIEW STUDENTVIEW
GO
--XEM DN VIEW

SELECT *
FROM MARK

INSERT INTO MARK VALUES('A001','HDJ',20,20,20)
SP_HELPTEXT STUDENTVIEW

SELECT *
FROM STUDENTVIEW

--XEM CAC DOI TUONG DUOC THAM CHIEU BOI VIEW
SP_DEPENDS STUDENTVIEW

--MA HOA VIEW
ALTER VIEW STUDENTVIEW
WITH ENCRYPTION
AS
SELECT S.FULLNAME
FROM STUDENT S INNER JOIN MARK M
ON S.ROLLNO = M.ROLLNO
WHERE M.MARK >= 10
--VIEW HIEN THI THONG TIN VE DIEM CUA SV VOI MARK>=10
DROP VIEW MARKVIEW

CREATE VIEW MARKVIEW
AS
SELECT *
FROM MARK
WHERE MARK >= 10
WITH CHECK OPTION

SELECT * 
FROM  MARKVIEW
--GIAM MARK DI 5 DIEM
UPDATE MARKVIEW
SET MARK = MARK - 5

SELECT * INTO MARKTEMP FROM MARK
DROP VIEW MARKTEMPVIEW
CREATE VIEW MARKTEMPVIEW
WITH SCHEMABINDING
AS
SELECT ROLLNO,MARK FROM DBO.MARKTEMP
--XOA DI BANG MARKTEMP
DROP TABLE MARKTEMP
--XEM DL TU VIEW
SELECT * 
FROM MARKTEMPVIEW
--TAO CHI MUC TREN MARKTEMPVIEW
CREATE UNIQUE CLUSTERED INDEX IX_MARKTEMPVIEW
ON MARKTEMPVIEW(ROLLNO) 
--VIEW TAO TU 01 BANG

--TAO VIEW
CREATE VIEW MARKTEMPVIEW

AS
SELECT * FROM MARKTEMP
--THEM DL VAO BANG MARKTEMP THONG QUA MARKTEMPVIEW(OK)
INSERT INTO MARKTEMPVIEW VALUES ('A009','C',10,10,10)
--XOA DI TU MARKTEMPVIEW SV CO MARK <= 10
DELETE FROM MARKTEMPVIEW 
WHERE MARK <= 10

--VIEW TAO TU NHIEU BANG
DROP VIEW STUDENTVIEW

CREATE VIEW STUDENTVIEW
AS
SELECT S.*,M.SUBJECTCODE,M.MARK
FROM STUDENT S INNER JOIN MARK M
ON S.ROLLNO = M.ROLLNO

SELECT * 
FROM STUDENTVIEW
SELECT *
FROM STUDENT
INSERT INTO STUDENTVIEW(ROLLNO,CLASSCODE,FULLNAME,MALE,
BIRTHDATE,ADDRESS,EMAIL) VALUES
('A0002','C0611L','THANH TRONG',1,'10/21/1983',
'HA TAY','TRONG@FPT.COM.VN')